import {ITypeMap} from '../../schema/generated/resolvers';

import {QueryParent} from '../Query';
import {MutationParent} from '../Mutation';
import {SubscriptionParent} from '../Subscription';
import {ExperienceParent} from '../Experience';
import {RestaurantParent} from '../Restaurant';
import {ReservationParent} from '../Reservation';
import {NeighbourhoodParent} from '../Neighbourhood';
import {ExperiencesByCityParent} from '../ExperiencesByCity';
import {ViewerParent} from '../Viewer';
import {LocationParent} from '../Location';
import {UserParent} from '../User';
import {OrderParent} from '../Order';
import {CityParent} from '../City';
import {PictureParent} from '../Picture';
import {ExperienceCategoryParent} from '../ExperienceCategory';
import {ReviewParent} from '../Review';
import {NotificationParent} from '../Notification';
import {PaymentAccountParent} from '../PaymentAccount';
import {MessageParent} from '../Message';
import {PaymentParent} from '../Payment';
import {PaypalInformationParent} from '../PaypalInformation';
import {PaytmInformationParent} from '../PaytmInformation';
import {DebitCardInformationParent} from '../DebitCardInformation';
import {CreditCardInformationParent} from '../CreditCardInformation';
import {PoliciesParent} from '../Policies';
import {MenuItemParent} from '../MenuItem';
import {PricingParent} from '../Pricing';
import {AuthPayloadParent} from '../AuthPayload';
import {MutationResultParent} from '../MutationResult';
import {CitySubscriptionPayloadParent} from '../CitySubscriptionPayload';
import {CityPreviousValuesParent} from '../CityPreviousValues';

import {Context} from './Context';

export interface TypeMap extends ITypeMap {
  Context: Context;
  QueryParent: QueryParent;
  MutationParent: MutationParent;
  SubscriptionParent: SubscriptionParent;
  ExperienceParent: ExperienceParent;
  RestaurantParent: RestaurantParent;
  ReservationParent: ReservationParent;
  NeighbourhoodParent: NeighbourhoodParent;
  ExperiencesByCityParent: ExperiencesByCityParent;
  ViewerParent: ViewerParent;
  LocationParent: LocationParent;
  UserParent: UserParent;
  OrderParent: OrderParent;
  CityParent: CityParent;
  PictureParent: PictureParent;
  ExperienceCategoryParent: ExperienceCategoryParent;
  ReviewParent: ReviewParent;
  NotificationParent: NotificationParent;
  PaymentAccountParent: PaymentAccountParent;
  MessageParent: MessageParent;
  PaymentParent: PaymentParent;
  PaypalInformationParent: PaypalInformationParent;
  PaytmInformationParent: PaytmInformationParent;
  DebitCardInformationParent: DebitCardInformationParent;
  CreditCardInformationParent: CreditCardInformationParent;
  PoliciesParent: PoliciesParent;
  MenuItemParent: MenuItemParent;
  PricingParent: PricingParent;
  AuthPayloadParent: AuthPayloadParent;
  MutationResultParent: MutationResultParent;
  CitySubscriptionPayloadParent: CitySubscriptionPayloadParent;
  CityPreviousValuesParent: CityPreviousValuesParent;
}
